// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAHWeSxij5rxiWmneRjWUCMF0VN3lATDs',
    appId: '1:602140514018:web:c4c985117786932ed030bb',
    messagingSenderId: '602140514018',
    projectId: 'elearning-97c12',
    authDomain: 'elearning-97c12.firebaseapp.com',
    storageBucket: 'elearning-97c12.appspot.com',
    measurementId: 'G-WY96TBNBVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu-eDwgH1_Nw4YdJqwu5apFQ0H0QyhyxI',
    appId: '1:602140514018:android:bbb8a4869e2c03dad030bb',
    messagingSenderId: '602140514018',
    projectId: 'elearning-97c12',
    storageBucket: 'elearning-97c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBosylJLNmef3Ss9EyAGIPGjRC4COe7wNQ',
    appId: '1:602140514018:ios:fa9cf8d0418349d9d030bb',
    messagingSenderId: '602140514018',
    projectId: 'elearning-97c12',
    storageBucket: 'elearning-97c12.appspot.com',
    androidClientId: '602140514018-2poauoj8cc7pg5cber930nifs9p3a17n.apps.googleusercontent.com',
    iosClientId: '602140514018-7a2hnl6mfii6bqt0bmj7mk3apbh3chkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBosylJLNmef3Ss9EyAGIPGjRC4COe7wNQ',
    appId: '1:602140514018:ios:fa9cf8d0418349d9d030bb',
    messagingSenderId: '602140514018',
    projectId: 'elearning-97c12',
    storageBucket: 'elearning-97c12.appspot.com',
    androidClientId: '602140514018-2poauoj8cc7pg5cber930nifs9p3a17n.apps.googleusercontent.com',
    iosClientId: '602140514018-7a2hnl6mfii6bqt0bmj7mk3apbh3chkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning',
  );
}
